### ISSUE TITLE
Error on configuring the plugin

### ISSUE THREAD

**Issue by GR360RY** [amiracle/homemonitor#7] opened 2016-04-09 19:23 UTC
Initial configuration fails with the following error:
```
Encountered the following error while trying to update: In handler 'localapps': Error while posting to url=/servicesNS/nobody/homemonitor/data/transforms/extractions/yourdevice
```
![screen shot 2016-04-09 at 22 19 34](https://cloud.githubusercontent.com/assets/828309/14405877/8d1534ce-fea1-11e5-9866-937f494e79ad.png)

**Comment by amiracle** [comment] 2016-04-12 18:42
Can you tell me on what OS you are running your Splunk server? Are you running as root/administrator? Lastly, what do you get when you type in https://<yoursplunkserver>:8089 ?

-Kam

**Comment by amiracle** [comment] 2016-08-23 01:24
Fixed with this workaround: 


HM Fix

Root Cause:
The problem is that the UDP 514 port is already enabled and data is coming in for syslog.  

Fix (workaround)

We just need to setup syslog to send data into Splunk and the home monitor index from your router. Let’s start by going to the $SPLUNK_HOME/etc/apps/homemonitor/local directory and making the changes to the config files there.  If the local directory does not exist, create it and add the following files: props.conf, transforms.conf, app.conf.  Let’s now modify the following files app.conf, transforms.conf and props.conf:

Add the following to `app.conf`:

    [install]
    is_configured = 1


Go to Settings -> Data Input -> UDP, click on 514 and then Advanced Settings, what is the Set Host component set to, IP, DNS or None? If it’s set to DNS, then use the the FQDN as the host, otherwise use the IP.  For example, if it’s set to IP and the IP is 192.168.1.1, the entry will look like this [host::192.168.1.1] .  Now let’s modify your props.conf:

Add the following to `props.conf:`

    [host::192.168.1.1]
    TRANSFORMS-homemonitor = index_redirect_to_homemonitor

Add the following line to `transforms.conf`:

    [index_redirect_to_homemonitor]
    REGEX = .
    DEST_KEY = _MetaData:Index
    FORMAT = homemonitor

Finally, in the inputs.conf file in the `$SPLUNK_HOME/etc/apps/homemonitor/default`, modify the stanza [udp://514] to have `disabled = 0` instead of `disabled = 1`.

Restart Splunk and the Home Monitor App should be able to be configured with your device source type and enable the bandwidth monitor. If you want to enable the bandwidth monitor for Windows, you just need to add the following stanza to your local `inputs.conf`: 

    [script://$SPLUNK_HOME\etc\apps\homemonitor\bin\speedtest.bat]
    disabled=0

I am aware that the fix current involves making a change to the default `inputs.conf`, but I will fix that in a later version of the app. 

Thanks,
Kam

**Closed by amiracle** 2016-08-23 01:24 UTC
Labels: bug
